# Generated by Django 4.1.7 on 2023-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerecorditem',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
