version: "3.9"

services:
  duck:
    container_name: duck_back
    build: .
    restart: unless-stopped
    command: uvicorn --host 0.0.0.0 --port 8080 --workers 4 asgi:application
    volumes:
      - duck_static_volume:/home/duck/staticfiles
      - duck_media_volume:/home/duck/media
      - duck_db_volume:/home/duck/db
    expose:
      - "8080"
    env_file:
      - .env
  nginx:
    container_name: duck_nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "${VIRTUAL_PORT}"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/duck/staticfiles
      - media_volume:/home/duck/media
    depends_on:
      - duck
    networks:
      - nginx-proxy
      - duck

volumes:
  duck_static_volume:
  duck_media_volume:
  duck_db_volume:

networks:
  nginx-proxy:
    external:
      name: net-nginx-proxy